### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [Vonage/vonage-java-code-snippets#80]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential security problem.

**My disclosures always follow Github's 90-day [disclosure policy](https://securitylab.github.com/advisories#policy) (I'm not an employee of Github, I just like their policy).**

**Comment by dragonmantank** [comment]
You have been invited to the security advisory.

Please keep in mind that this repository is code for illustrative purposes and not distributed as production-quality or as a library, so a public PR might just be as valid and a quicker fix than going through a full security advisory.
