### ISSUE TITLE
Invoke Dynamic Not Supported

### ISSUE THREAD

**Issue by oseamiya** [Vonage/vonage-java-code-snippets#82]
I am getting this error 'Invoke Dynamic Not supported' while building the application.
This is error.
![image](https://user-images.githubusercontent.com/85782575/123430876-6515f980-d5e8-11eb-945c-a4e2169642db.png)

**Comment by oseamiya** [comment]
This is probably due to  Dex does not support Java 8 constructs. So to fix the issues, you should rewrites Java 8 bytecode to Java 7 that Dex can understand.

**Comment by dragonmantank** [comment]
Unfortunately we do not support Java prior to 8, as Java 7 is no longer supported by Oracle.

On a side note in regards to Dex, these code snippets and our SDK are not designed for Android and are meant to be run under a server-side JVM. All the Java code in this repo, and in the SDK itself, would present a fairly large security issue when deployed to a client device, as your credentials can easily be extracted.
