### ISSUE TITLE
Compile problem with test code

### ISSUE THREAD

**Issue by mgodbole** [Vonage/vonage-java-code-snippets#89]
I am trying out the test code.

Created a maven project.
Added the Vonage maven dependency
		<dependency>
			<groupId>com.vonage</groupId>
			<artifactId>client</artifactId>
			<version>7.1.0</version>
		</dependency>

Copied the sample code from https://github.com/vonage/vonage-java-code-snippets/blob/master/src/main/java/com/vonage/quickstart/voice/OutboundTextToSpeechWithNcco.java#L39-L42

But I am getting an error on this line.
Ncco ncco = new Ncco(TalkAction.builder("This is a text to speech call from Vonage").build());
_The type com.fasterxml.jackson.databind.ObjectWriter cannot be resolved. It is indirectly referenced from required .class files_

I checked maven repo and 7.1.0 is indeed the latest version.
What gives?

Thanks,
Maneesh

**Comment by SMadani** [comment]
Please try again with the latest version. This error seems like a classpath issue, most likely a problem with your `build.gradle` or `pom.xml` dependencies.
